# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/save.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(283, 158)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_export_quantiles = QtWidgets.QCheckBox(Dialog)
        self.cb_export_quantiles.setChecked(True)
        self.cb_export_quantiles.setObjectName("cb_export_quantiles")
        self.horizontalLayout.addWidget(self.cb_export_quantiles)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cb_export_quantiles_2 = QtWidgets.QCheckBox(Dialog)
        self.cb_export_quantiles_2.setChecked(True)
        self.cb_export_quantiles_2.setObjectName("cb_export_quantiles_2")
        self.horizontalLayout_3.addWidget(self.cb_export_quantiles_2)
        self.cb_classification = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_classification.sizePolicy().hasHeightForWidth())
        self.cb_classification.setSizePolicy(sizePolicy)
        self.cb_classification.setMaximumSize(QtCore.QSize(190, 16777215))
        self.cb_classification.setObjectName("cb_classification")
        self.cb_classification.addItem("")
        self.cb_classification.addItem("")
        self.cb_classification.addItem("")
        self.cb_classification.addItem("")
        self.horizontalLayout_3.addWidget(self.cb_classification)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.but_fout = QtWidgets.QPushButton(Dialog)
        self.but_fout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.but_fout.setIcon(icon)
        self.but_fout.setIconSize(QtCore.QSize(30, 30))
        self.but_fout.setDefault(True)
        self.but_fout.setObjectName("but_fout")
        self.horizontalLayout_2.addWidget(self.but_fout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Datei exportieren"))
        self.cb_export_quantiles.setText(_translate("Dialog", "Exportiere "))
        self.lineEdit.setText(_translate("Dialog", "10, 25, 50, 75, 90"))
        self.label.setText(_translate("Dialog", "Quantile"))
        self.cb_export_quantiles_2.setText(_translate("Dialog", "Exportiere Klassen nach"))
        self.cb_classification.setItemText(0, _translate("Dialog", "Freedman–Diaconis"))
        self.cb_classification.setItemText(1, _translate("Dialog", "Square-Root"))
        self.cb_classification.setItemText(2, _translate("Dialog", "Sturges"))
        self.cb_classification.setItemText(3, _translate("Dialog", "Rice"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
