{
    'Integer identifying grain': 'n',
    'Average orientation (phi1, PHI, phi2) in degrees': 'ori-d',
    'Average orientation (phi1, PHI, phi2) in radians': 'ori-r',
    'Average Position (x, y) in microns': 'pos',
    'Average Image Quality (IQ)': 'iq',
    'Average Confidence Index (CI)': 'ci',
    'An integer identifying the phase': 'phase',
    'Edge grain (1) or interior grain (0)': 'edge',
    'Number of measurement points in the grain': 'points',
    'Area of grain in square microns': 'area',
    'Diameter of grain in microns': 'dia',
    'ASTM grain size': 'ASTM',
    'Aspect ratio of ellipse fit to grain': 'aspect',
    'Length of major axis of ellipse fit to grain in microns': 'majEll',
    'Length of minor axis of ellipse fit to grain in microns': 'minEll',
    'Orientation (relative to the horizontal) of major axis of ellipse fit to grain in degrees': 'relOr',
    'Grain ellipticity': 'ellipt',
    'Grain circularity': 'circul',
    'Maximmum Feret diameter': 'maxFeret',
    'Minimum Feret diameter': 'minFeret',
    'Average orientation spread in grain (average misorientation of all point pairs)': 'avOrSpread'
}